import type { EquipmentItem } from "./types";

export const equipmentItems = [
  { id: "eq-axiograph", slug: "axiograph", name: "Электронный аксиограф", description: "Цифровой прибор для анализа траекторий движения нижней челюсти и работы ВНЧС.", patientBenefit: "Точная диагностика причин боли или дискомфорта в суставе и индивидуально подобранное лечение.", image: "https://images.pexels.com/photos/3845722/pexels-photo-3845722.jpeg?auto=compress&cs=tinysrgb&w=1000" },
  { id: "eq-microscope", slug: "microscope", name: "Дентальный операционный микроскоп", description: "Оптическая система с многократным увеличением и бестеневым освещением.", patientBenefit: "Бережное сохранение тканей зуба, обнаружение скрытых каналов и точная реставрация.", image: "https://images.pexels.com/photos/3845766/pexels-photo-3845766.jpeg?auto=compress&cs=tinysrgb&w=1000" },
  { id: "eq-ct", slug: "3d-ct-scan", name: "3D-компьютерный томограф", description: "Высокоточный конусно-лучевой томограф с минимальной лучевой нагрузкой.", patientBenefit: "Безопасная 3D-модель челюсти для точного планирования имплантации и хирургии.", image: "https://images.pexels.com/photos/4270371/pexels-photo-4270371.jpeg?auto=compress&cs=tinysrgb&w=1000" },
  { id: "eq-intraoral-scanner", slug: "intraoral-scanner", name: "Интраоральный 3D-сканер", description: "Компактная камера создаёт точные цифровые слепки зубных рядов в реальном времени.", patientBenefit: "Лечение без слепочных масс с мгновенной визуализацией будущей улыбки.", image: "https://images.pexels.com/photos/3845736/pexels-photo-3845736.jpeg?auto=compress&cs=tinysrgb&w=1000" },
  { id: "eq-digital-diagnostics", slug: "digital-diagnostics", name: "Digital Smile Design", description: "Система лицевого анализа и виртуального моделирования формы зубов.", patientBenefit: "Возможность заранее увидеть планируемый результат новой улыбки.", image: "https://images.pexels.com/photos/3845810/pexels-photo-3845810.jpeg?auto=compress&cs=tinysrgb&w=1000" },
  { id: "eq-sterilization", slug: "autoclave-sterilization", name: "Автоклав класса B", description: "Автоматизированная система стерилизации с фракционированным вакуумом.", patientBenefit: "Инфекционная безопасность инструментов в индивидуальном герметичном пакете.", image: "https://images.pexels.com/photos/6627618/pexels-photo-6627618.jpeg?auto=compress&cs=tinysrgb&w=1000" },
] as const satisfies readonly EquipmentItem[];
