import type { TeamMember } from "./types";

export const teamMembers = [
  {
    id: "doc-shodmonov",
    slug: "shodmonov-sabur",
    name: "Шодмонов Сабур",
    category: "doctors",
    position: "Врач-стоматолог, терапевт-ортопед",
    shortBio: "Эксперт в области функциональной и эстетической стоматологии, цифрового проектирования улыбки и тотальных реставраций.",
    image: "https://i.ibb.co/whR8CjHF/Shodmonov-Sabur.jpg",
    experienceYears: "Более 8 лет",
    specialties: ["Функциональная стоматология", "Эстетическая реставрация", "Терапия и ортопедия"],
  },
  {
    id: "doc-ahmedova",
    slug: "ahmedova-ruhshona",
    name: "Ахмедова Рухшона",
    category: "doctors",
    position: "Врач-стоматолог первой категории",
    shortBio: "Специализируется на детской стоматологии, адаптивной гигиене и бережном лечении без боли.",
    image: "https://i.ibb.co/sJ3yNLTB/Ahmedova-Ruhshona.jpg",
    experienceYears: "13 лет",
    specialties: ["Детская стоматология", "Адаптивная гигиена", "Лечение без боли"],
  },
  {
    id: "doc-nazarov",
    slug: "nazarov-somon",
    name: "Назаров Сомон",
    category: "doctors",
    position: "Врач-стоматолог-терапевт, ортопед",
    shortBio: "Лечит сложные случаи корневых каналов с применением дентального микроскопа и микрохирургии.",
    image: "https://i.ibb.co/LTG7YNr/Nazarov-Somon.jpg",
    experienceYears: "Специализация: сложная эндодонтия",
    specialties: ["Сложная эндодонтия", "Лечение под микроскопом", "Ортопедическое восстановление"],
  },
  {
    id: "doc-kosimov",
    slug: "kosimov-husrav",
    name: "Косимов Хусрав",
    category: "doctors",
    position: "Врач-стоматолог терапевт-ортопед",
    shortBio: "Специализируется на художественных реставрациях всех групп зубов.",
    image: "https://i.ibb.co/tpGBsMFm/Kosimov-Husrav.jpg",
    specialties: ["Художественная реставрация", "Терапевтическое лечение", "Ортопедия"],
  },
  {
    id: "doc-bekova",
    slug: "bekova-aziza",
    name: "Бекова Азиза",
    category: "doctors",
    position: "Врач стоматолог-ортодонт",
    shortBio: "Специализируется на исправлении прикуса элайнерами и брекетами у детей и взрослых.",
    image: "https://i.ibb.co/s9wF2yFP/Bekova-Aziza.jpg",
    experienceYears: "5 лет",
    specialties: ["Ортодонтия", "Детская ортодонтия", "Исправление прикуса"],
  },
  {
    id: "doc-bashirov",
    slug: "bashirov-amin",
    name: "Баширов Амин",
    category: "doctors",
    position: "Врач стоматолог-хирург",
    shortBio: "Специализируется на имплантологии и костно-пластических операциях повышенной сложности.",
    image: "https://i.ibb.co/VWwPCynt/Bashirov-Amin.jpg",
    specialties: ["Хирургическая стоматология", "Имплантология", "Костная пластика"],
  },
  {
    id: "nurse-1",
    slug: "zarina-yusupova",
    name: "Зарина Юсупова",
    category: "nurses",
    position: "Старшая медицинская сестра",
    shortBio: "Обеспечивает строгие стандарты асептики, антисептики и стерилизационного режима.",
    image: "https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 10,
    specialties: ["Стерилизация и асептика", "Ассистирование в хирургии"],
  },
  {
    id: "nurse-2",
    slug: "shahnoza-alieva",
    name: "Шахноза Алиева",
    category: "nurses",
    position: "Медицинская сестра-ассистент",
    shortBio: "Заботливо ассистирует в четыре руки на терапевтических и детских приёмах.",
    image: "https://images.pexels.com/photos/3714743/pexels-photo-3714743.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 6,
  },
  {
    id: "admin-1",
    slug: "dilnoza-safarova",
    name: "Дильноза Сафарова",
    category: "administrators",
    position: "Старший администратор клиники",
    shortBio: "Координирует графики приёмов и помогает пациентам оформить необходимые документы.",
    image: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 7,
  },
  {
    id: "admin-2",
    slug: "tahmina-nurova",
    name: "Тахмина Нурова",
    category: "administrators",
    position: "Администратор службы заботы",
    shortBio: "Помогает с записью, организацией консультаций и туристическим сервисом.",
    image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 5,
  },
  {
    id: "mgmt-1",
    slug: "farhod-rahimov",
    name: "Фарход Рахимов",
    category: "management",
    position: "Генеральный директор Family Dent",
    shortBio: "Развивает стандарты сервиса, технологическое оснащение и международное сотрудничество клиники.",
    image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 15,
  },
  {
    id: "mgmt-2",
    slug: "sevara-sodikova",
    name: "Севара Содикова",
    category: "management",
    position: "Исполнительный директор",
    shortBio: "Отвечает за бесперебойную работу подразделений и качество обслуживания пациентов.",
    image: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 12,
  },
  {
    id: "tech-1",
    slug: "firdavs-ikromov",
    name: "Фирдавс Икромов",
    category: "technical",
    position: "Главный инженер медицинского оборудования",
    shortBio: "Отвечает за калибровку КТ, микроскопов, сканеров и инженерных систем.",
    image: "https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 9,
  },
  {
    id: "tech-2",
    slug: "bakhtiyor-nodiri",
    name: "Бахтиёр Нодири",
    category: "technical",
    position: "Руководитель хозяйственной службы",
    shortBio: "Поддерживает безупречную чистоту, уют и экологическую безопасность пространств клиники.",
    image: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=800",
    experienceYears: 11,
  },
] as const satisfies readonly TeamMember[];
