export const page = "min-h-screen bg-background pb-24";
export const container = "container mx-auto px-4 sm:px-6 lg:px-8";
export const header = "max-w-3xl mb-16 pb-10 border-b border-border";
export const badge = "inline-flex items-center gap-3 text-primary text-xs font-semibold uppercase tracking-[0.18em] mb-5 before:content-[''] before:block before:w-10 before:h-px before:bg-primary";
export const title = "font-heading text-4xl sm:text-5xl lg:text-6xl font-semibold text-foreground leading-[1.08] mb-5 text-balance";
export const titleSpan = "text-primary";
export const desc = "text-lg text-muted-foreground leading-relaxed";
export const grid = "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8";
export const card = "group bg-card rounded-md overflow-hidden shadow-md hover:shadow-md transition-shadow duration-300 border-0 flex flex-col h-full";
export const imageWrapper = "aspect-[16/10] overflow-hidden";
export const cardContent = "p-8 flex flex-col flex-1";
export const meta = "flex items-center gap-6 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground mb-4";
export const cardTitle = "text-2xl font-semibold text-foreground mb-4 group-hover:text-primary transition-colors line-clamp-2";
export const cardDesc = "text-muted-foreground text-sm leading-relaxed mb-6 line-clamp-3";
export const link = "mt-auto inline-flex items-center gap-2 text-primary font-semibold uppercase tracking-[0.18em] text-[10px] sm:text-xs group/link"
