export const page = "min-h-screen bg-white pt-24 sm:pt-28 lg:pt-32";
export const container = "container mx-auto px-4 sm:px-6 lg:px-8";
export const breadcrumbWrapper = "pt-8 pb-4";
export const breadcrumb = "flex items-center gap-2 text-sm text-slate-500";
export const breadcrumbLink = "hover:text-primary transition-colors flex items-center gap-1";
export const breadcrumbActive = "text-slate-900 font-medium";
export const specialtyBadge = "inline-block bg-primary/10 text-primary text-[10px] sm:text-xs font-bold uppercase tracking-[0.2em] px-4 py-1.5 rounded-full mb-6 self-start border-0";
export const title = "text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-slate-900 mb-6 sm:mb-8 leading-tight";
export const descBlock = "bg-slate-50 p-8 sm:p-12 rounded-[40px] mb-12 border border-slate-100/50";
export const descText = "text-lg sm:text-xl text-slate-600 leading-relaxed italic";
export const infoCard = "p-8 rounded-[32px] bg-white border border-slate-100 shadow-sm hover:shadow-md transition-shadow";
export const infoHeader = "flex items-center gap-4 mb-6";
export const infoIcon = "w-12 h-12 rounded-2xl bg-primary/5 flex items-center justify-center text-primary";
export const infoTitle = "text-xl font-bold text-slate-900";
export const infoItem = "text-slate-600 flex items-start gap-4";
export const infoBullet = "w-2 h-2 rounded-full bg-primary mt-2.5 shrink-0";
export const infoContent = "font-medium leading-relaxed";
export const buttonGroup = "flex flex-wrap gap-4 mt-12";
export const bookButton = "h-14 sm:h-18 px-8 sm:px-12 rounded-2xl sm:rounded-3xl bg-primary text-white text-lg sm:text-xl font-bold shadow-xl shadow-primary/20 hover:scale-[1.02] active:scale-95 transition-all flex items-center justify-center"
