export const section = 'relative pt-24 pb-14 lg:pt-28 lg:pb-16 bg-white overflow-hidden';
export const container = 'container mx-auto px-4 sm:px-6 lg:px-8 relative z-10';
export const layout = 'grid grid-cols-1 lg:grid-cols-[1.08fr_0.92fr] gap-10 lg:gap-12 items-center';
export const content = 'max-w-2xl';
export const badge = 'inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-[10px] font-black uppercase tracking-[0.18em] mb-5 border-0';
export const title = 'text-[clamp(2.1rem,4vw,4.6rem)] font-bold text-slate-900 leading-[1.05] mb-5 tracking-tight';
export const titleAccent = 'text-primary';
export const desc = 'text-base lg:text-lg text-slate-600 leading-relaxed mb-7 max-w-xl';
export const btnGroup = 'flex flex-col sm:flex-row gap-3 mb-8';
export const btnPrimary = 'h-12 px-6 rounded-xl bg-primary hover:bg-primary-hover text-white font-bold text-sm shadow-lg shadow-primary/20 flex items-center justify-center gap-2 active:scale-95 transition-all';
export const btnUrgent = 'h-12 px-6 rounded-xl border border-primary/25 bg-white hover:bg-primary/5 text-foreground font-bold text-sm flex items-center justify-center gap-2 active:scale-95 transition-all';
export const features = 'grid grid-cols-2 gap-4 max-w-xl';
export const featureItem = 'flex items-center gap-3 rounded-xl bg-secondary/70 border border-border p-3';
export const featureIcon = 'w-10 h-10 rounded-xl bg-white flex items-center justify-center text-primary shrink-0';
export const featureTitle = 'text-base font-bold text-slate-900 block';
export const featureSubtitle = 'text-slate-500 text-xs font-medium';
export const imageContainer = 'relative rounded-2xl overflow-hidden aspect-[5/4] lg:aspect-[4/4.1] max-h-[585px] shadow-xl shadow-slate-200';
export const image = 'w-full h-full object-cover';
export const floatingCard = 'absolute bg-white/95 backdrop-blur-md p-3 rounded-xl shadow-lg border border-white/70 flex items-center gap-3'
